let keywords = [
	"sequence",
	"pouring ::: 101 hats",
	"archive",
	"time",
	"mechanical computation",
	"electrical pulse logic",
	"wired equations",
	"analog recursion",
	"binary calculations",
	"vector",
	"drawing",
	"reading",
	"writing",
	"chance",
	"random numbers",
	"discrete",
	"continuous",
	"code",
	"algorithm",
	"language",
	"symbols",
	"grid",
	"matrix",
	"dimensions",
	"timeline",
	"webs",
	"networks",
	"relational joins",
	"hypertext",
	"counting",
	"wayfinding",
	"sculptural index",
	"imprint",
	"prayerful computation",
	"circle", "line",
	"rectangle",
	"static", "weather system",
	"radio", "telegraph",
	"nested", "lists",
	"word collation",
	"memex", "quipo",
	"scale", "trees", "webs",
	"directed graph", 
	"computation", "algebra",
	"calculus", "change",
	"encoded", "poetics",
];
let frictions = [
	["chance","deterministic"],
	["silence","revealed"],
	["open system", "closed system"],
	["noise", "harmonics"],
	["dissonance", "consonance"],
	["continuous", "discrete"],
	["infinite between", "finite ladders"],
	["real numbers", "counting numbers"],
	["rational numbers", "irrational numbers"],
	["opaque", "readable"],
	["vector", "raster"],
];
let abstracts = [
	{
		id: "20240316094300",
		keywords: ["sequence","time","vector","drawing"],
		title: "a sequence tool",
		subtitle: "notes0",
		date: "2024.03.16",
		credits: "mctavish",
		textlists: [
			[
				"a tool a mill a clock"
				"pages frames prints",
				"algorithmic press",
				"count map mark",
				"book of hours",
				"book of minutes",
				"book of seconds",
				"a tween ::: 24 steps",
				"between seconds",
				"between states",
				"between ticks",
				"multiples ratios",
				"tonal ladders",
				"recorded sound fragments",
				"knot filtered sound into threads",
				"fray twist knot",
				"braid threads into soundscape",
				"compile frames into animations",
				"weld sound to moving pictures",
			],
		]
	},
	{
		id: "20240316101400",
		keywords: ["drawing","diagram", "model"],
		title: "",
		subtitle: "notes0",
		date: "2024.03.16",
		credits: "mctavish",
		textlists: [
			[
				"model diagram index",
			],
			[
				"to draw ::: scrawl write",
				"vector manifesto",
				"hand mark thought",
				"a rendering ::: an imprint",


		]
	},
	{
		id: "20240327144900",
		keywords: ["reading"],
		title: "",
		subtitle: "notes",
		date: "2024.04.27",
		credits: "mctavish",
		textlists: [
			[
				"to read ::: a physical act",
				"climbing clamber grasp",
				"pull delve untangle",
				"uncover reveal knot fuse",
				"a traversal",
				"glyph word line page",
				"link",
				"index => search engine",
				"lost articulation",
				"conglomerates ::: statistical blobs",
				"versus hyper local or specific joins",
				"purposeful, transparant distillation",
				"versus opaque, black-box-variable compression",
				"defining the axes of distillation keeps the inquiry open",
				"keeps the bolts revealed ::: the cornices exposed",
				"the structure present",
				"a conceptual sarah zse architectural, blow-up sculpture",
				"a trans | media ::: space | time pop-up book",
			],

		]
	}
];
let links = [
	{
		title: "poetics of encryption",
		url: "https://www.kw-berlin.de/en/poetics-of-encryption-exhibition-24/",
		keywords: ["encyption", "encoded", "opacity", "surveilance"],
		date: "2024.03.16",
		description: "an exhibit at KW Studio: 2024",
	},
]
