let input =
	{
	"sequencetitle": "telegraph",
	"duration": 2,
	"nticks": 120,
	"fps": 24,
	"nx": 3,
	"ny": 3,
	"nz": 3,
	"xgrid": [
		0.5,
		0.5,
		0.5
	],
	"ygrid": [
		0.5,
		0.5,
		0.5
	],
	"pigments": {
		"red": "#AE0501",
		"yellow": "#ffcc00",
		"blue": "#006699",
		"bluegreen": "#006969",
		"darkbrown": "#332c21",
		"brown": "#4f4433",
		"black": "#000000",
		"warmblack": "#191918",
		"warmblack1": "#080807",
		"warmblack2": "#2E2E2C",
		"warmblack3": "#3B3B38",
		"warmblack4": "#4F4F4C",
		"warmblack5": "#545451",
		"warmblack6": "#61615D",
		"warmblack7": "#666662",
		"warmblack8": "#70706C",
		"warmblack9": "#7A7A76",
		"warmblack10": "#8C8C87",
		"warmblack11": "#999993",
		"warmblack12": "#ADADA6",
		"warmblack13": "#BDBDB5",
		"warmblack14": "#CCCCC4",
		"warmblack15": "#DBDBD3",
		"warmblack16": "#E6E6DC",
		"warmblack17": "#F0F0E6",
		"warmblack18": "#FAFAF0",
		"warmblack19": "#FCFCF2",
		"warmblack20": "#FFFFF5",
		"gray": "#484848",
		"lightgray": "#888888",
		"warmgray": "#4b4b44",
		"warmlightgray": "#656560",
		"white": "#ffffff",
		"warmwhite": "#fcfbe3",
		"warmlightwhite": "#fdfdf3",
		"warmlightwhite1": "#FFFFF5",
		"warmlightwhite2": "#FAFAF0",
		"warmlightwhite3": "#F5F5EB",
		"warmlightwhite4": "#F0F0E6",
		"warmlightwhite5": "#EBEBE1",
		"warmlightwhite6": "#E6E6DC",
		"warmlightwhite7": "#E0E0D7",
		"warmlightwhite8": "#D6D6CE",
		"warmlightwhite9": "#D1D1C9",
		"warmlightwhite10": "#CCCCC4",
		"warmlightwhite11": "#C7C7BF",
		"warmlightwhite12": "#C2C2BA",
		"warmlightwhite13": "#BDBDB5",
		"warmlightwhite14": "#B8B8B0",
		"warmlightwhite15": "#B3B3AB",
		"warmlightwhite16": "#ADADA6",
		"warmlightwhite17": "#A8A8A2",
		"warmlightwhite18": "#A3A39D",
		"warmlightwhite19": "#999993",
		"warmlightwhite20": "#8F8F89",
		"warmlightwhiteveil": "rgba(253,253,243,0.8)",
		"richblack": "#010203",
		"richgray1": "#2a2a2b",
		"richgray2": "#4f4f50",
		"richgray3": "#777878",
		"richgray4": "#a2a3a3",
		"richgray5": "#d0d0d0",
		"richgray6": "#ffffff",
		"philippurple1": "#1A0D73",
		"philippurple2": "#59518C",
		"philippurple3": "#131159",
		"philipgreen1": "#3E5915",
		"philipgreen2": "#708C32"
	},
	"corecolors": [
		"#191918",
		"#fdfdf3"
	],
	"spicecolors": [
		"#191918",
		"#fdfdf3"
	],
	"allcolors": [
		"#191918",
		"#fdfdf3",
		"#191918",
		"#fdfdf3"
	],
	"weightedcolors": [
		"var(--corecolor0)",
		"var(--corecolor0)",
		"var(--corecolor0)",
		"var(--corecolor0)",
		"var(--corecolor0)",
		"var(--corecolor0)",
		"var(--corecolor0)",
		"var(--corecolor0)",
		"var(--corecolor0)",
		"var(--corecolor0)",
		"var(--corecolor1)",
		"var(--corecolor1)",
		"var(--corecolor1)",
		"var(--corecolor1)",
		"var(--corecolor1)",
		"var(--corecolor1)",
		"var(--corecolor1)",
		"var(--corecolor1)",
		"var(--corecolor1)",
		"var(--spicecolor0)",
		"var(--spicecolor1)",
		"var(--spicecolor1)",
		"var(--spicecolor2)",
		"var(--spicecolor2)"
	],
	"cssstyles": "",
	"npoems": 80,
	"nstanzas": 3,
	"nlines": 4,
	"nchars": 48,
	"weights": [
		0,
		18,
		22,
		22,
		30,
		24,
		18,
		16,
		14,
		12,
		6,
		4,
		3,
		2,
		2,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1
	],
	"bookinfo": {
		"sequencetitle": "telegraph",
		"title": "telegraph",
		"subtitle": "Sat Jul 20 2024",
		"description": "algorithmic sound & drawings",
		"rooturl": "https://telegraph.work",
		"authorurl": "https://mctavish.work/",
		"author": "mctavish",
		"copyright": "Copyright ©2024 mctavish<br/>",
		"isbn": "ISBN: 00000<br/>",
		"publisher": ". . .",
		"bodyclasses": [
			"illustratedbook"
		],
		"ntickstitle": 1,
		"fps": 1,
		"nticks": 60,
		"sections": [],
		"poemids": [],
		"bookunits": "in",
		"width": 8,
		"height": 8,
		"margin": 1,
		"guttermargin": 1,
		"bleed": 0.125,
		"spine": 0.322,
		"pixelsperunit": 72,
		"svgwidth": 576,
		"svgheight": 576,
		"captionheight": 1,
		"cssstyles": ""
	},
	"postcardinfo": {
		"sequencetitle": "telegraph",
		"title": "telegraph",
		"subtitle": "Sat Jul 20 2024",
		"description": "algorithmic sound & drawings",
		"rooturl": "https://telegraph.work",
		"authorurl": "https://mctavish.work/",
		"author": "mctavish",
		"copyright": "Copyright ©2024 mctavish<br/>",
		"isbn": "ISBN: 00000<br/>",
		"publisher": ". . .",
		"bodyclasses": [
			"broadsides",
			"notext"
		],
		"ntickstitle": 1,
		"nticks": 60,
		"fps": 1,
		"sections": [],
		"poemids": [],
		"bookunits": "in",
		"width": 6,
		"height": 4,
		"margin": 0.5,
		"guttermargin": 0.5,
		"bleed": 0.125,
		"spine": 0.322,
		"pixelsperunit": 72,
		"svgwidth": 504,
		"svgheight": 360,
		"captionheight": 1,
		"cssstyles": ""
	},
	"coverinfo": {
		"sequencetitle": "telegraph",
		"title": "telegraph",
		"subtitle": "Sat Jul 20 2024",
		"description": "algorithmic sound & drawings",
		"rooturl": "https://telegraph.work",
		"authorurl": "https://mctavish.work/",
		"author": "mctavish",
		"copyright": "Copyright ©2024 mctavish<br/>",
		"isbn": "ISBN: 00000<br/>",
		"publisher": ". . .",
		"bodyclasses": [
			"film",
			"notext"
		],
		"ntickstitle": 1,
		"fps": 1,
		"nticks": 60,
		"sections": [],
		"poemids": [],
		"bookunits": "in",
		"width": 16.572,
		"height": 8.25,
		"margin": 0,
		"guttermargin": 0,
		"bleed": 0.125,
		"spine": 0.322,
		"pixelsperunit": 72,
		"svgwidth": 1193.184,
		"svgheight": 617.184,
		"captionheight": 1,
		"cssstyles": ""
	},
	"picture8x8info": {
		"sequencetitle": "telegraph",
		"title": "telegraph",
		"subtitle": "Sat Jul 20 2024",
		"description": "algorithmic sound & drawings",
		"rooturl": "https://telegraph.work",
		"authorurl": "https://mctavish.work/",
		"author": "mctavish",
		"copyright": "Copyright ©2024 mctavish<br/>",
		"isbn": "ISBN: 00000<br/>",
		"publisher": ". . .",
		"bodyclasses": [
			"film",
			"notext"
		],
		"ntickstitle": 1,
		"nticks": 24,
		"fps": 1,
		"sections": [],
		"poemids": [],
		"bookunits": "in",
		"width": 8,
		"height": 8,
		"margin": 0,
		"guttermargin": 0,
		"bleed": 0.125,
		"spine": 0.322,
		"pixelsperunit": 120,
		"svgwidth": 960,
		"svgheight": 960,
		"captionheight": 1,
		"cssstyles": ""
	},
	"picturebookinfo": {
		"sequencetitle": "telegraph",
		"title": "telegraph",
		"subtitle": "Sat Jul 20 2024",
		"description": "algorithmic sound & drawings",
		"rooturl": "https://telegraph.work",
		"authorurl": "https://mctavish.work/",
		"author": "mctavish",
		"copyright": "Copyright ©2024 mctavish<br/>",
		"isbn": "ISBN: 00000<br/>",
		"publisher": ". . .",
		"bodyclasses": [
			"broadsides notext"
		],
		"ntickstitle": 1,
		"fps": 1,
		"nticks": 120,
		"sections": [],
		"poemids": [],
		"bookunits": "in",
		"width": 8,
		"height": 8,
		"margin": 1,
		"guttermargin": 1,
		"bleed": 0.125,
		"spine": 0.322,
		"pixelsperunit": 72,
		"svgwidth": 576,
		"svgheight": 576,
		"captionheight": 1,
		"cssstyles": ""
	},
	"film9x9info": {
		"sequencetitle": "telegraph",
		"title": "telegraph",
		"subtitle": "Sat Jul 20 2024",
		"description": "algorithmic sound & drawings",
		"rooturl": "https://telegraph.work",
		"authorurl": "https://mctavish.work/",
		"author": "mctavish",
		"copyright": "Copyright ©2024 mctavish<br/>",
		"isbn": "ISBN: 00000<br/>",
		"publisher": ". . .",
		"bodyclasses": [
			"film",
			"notext"
		],
		"ntickstitle": 0,
		"nticks": 120,
		"fps": 24,
		"sections": [],
		"poemids": [],
		"bookunits": "in",
		"width": 9,
		"height": 9,
		"margin": 0,
		"guttermargin": 0,
		"bleed": 0,
		"spine": 0,
		"pixelsperunit": 120,
		"svgwidth": 1080,
		"svgheight": 1080,
		"captionheight": 1,
		"cssstyles": ""
	},
	"film16x9info": {
		"sequencetitle": "telegraph",
		"title": "telegraph",
		"subtitle": "Sat Jul 20 2024",
		"description": "algorithmic sound & drawings",
		"rooturl": "https://telegraph.work",
		"authorurl": "https://mctavish.work/",
		"author": "mctavish",
		"copyright": "Copyright ©2024 mctavish<br/>",
		"isbn": "ISBN: 00000<br/>",
		"publisher": ". . .",
		"bodyclasses": [
			"film",
			"notext"
		],
		"ntickstitle": 0,
		"nticks": 120,
		"fps": 24,
		"sections": [],
		"poemids": [],
		"bookunits": "in",
		"width": 16,
		"height": 9,
		"margin": 0,
		"guttermargin": 0,
		"bleed": 0,
		"spine": 0,
		"pixelsperunit": 120,
		"svgwidth": 1920,
		"svgheight": 1080,
		"captionheight": 1,
		"cssstyles": ""
	}
};
module.exports = input;