let input =
	{
	"duration": 3.8,
	"fps": 24,
	"sounds": [
		{
			"id": "longbell",
			"keywords": "bell|afterring|long",
			"file": "longbell.mp3",
			"duration": 18.865011,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "bell11",
			"keywords": "bell|afterring",
			"file": "bell11.mp3",
			"duration": 20.119002,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "bell13",
			"keywords": "bell|afterring",
			"file": "bell13.mp3",
			"duration": 13.901995,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "bell2",
			"keywords": "bell|afterring",
			"file": "bell2.mp3",
			"duration": 5.438005,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "bell6",
			"keywords": "bell|afterring",
			"file": "bell6.mp3",
			"duration": 11.890998,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "bell9",
			"keywords": "bell|afterring",
			"file": "bell9.mp3",
			"duration": 12.178005,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "374272__samulis__tubular-bells-e5-tb_hit_f5_v3_rr1",
			"keywords": "orchinstsample|bell|afterring",
			"file": "374272__samulis__tubular-bells-e5-tb_hit_f5_v3_rr1.mp3",
			"duration": 4.649002,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "374273__samulis__tubular-bells-c4-tb_hit_c4_v4_rr1",
			"keywords": "orchinstsample|bell|afterring",
			"file": "374273__samulis__tubular-bells-c4-tb_hit_c4_v4_rr1.mp3",
			"duration": 11.937007,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "375552__samulis__gong-gong_scrape_3",
			"keywords": "orchinstsample|bell|bowedmetal",
			"file": "375552__samulis__gong-gong_scrape_3.mp3",
			"duration": 1.097007,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "373178__samulis__f-horn-muted-sustain-g4-mohorn_mute_g3_v1_1",
			"keywords": "orchinstsample|brass|horn|long",
			"file": "373178__samulis__f-horn-muted-sustain-g4-mohorn_mute_g3_v1_1.mp3",
			"duration": 8.385011,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "373243__samulis__f-horn-sustain-a3-mohorn_sus_a2_v1_1",
			"keywords": "orchinstsample|brass|horn|long",
			"file": "373243__samulis__f-horn-sustain-a3-mohorn_sus_a2_v1_1.mp3",
			"duration": 14.55,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "373253__samulis__f-horn-sustain-a3-mohorn_sus_a2_v2_1",
			"keywords": "orchinstsample|brass|horn|long",
			"file": "373253__samulis__f-horn-sustain-a3-mohorn_sus_a2_v2_1.mp3",
			"duration": 13.688005,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "bird0",
			"keywords": "bird|afterring",
			"file": "bird0.mp3",
			"duration": 6.588005,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "bird1",
			"keywords": "bird|afterring",
			"file": "bird1.mp3",
			"duration": 6.613991,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "bird2",
			"keywords": "bird|afterring",
			"file": "bird2.mp3",
			"duration": 6.613991,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "bird3",
			"keywords": "bird|afterring",
			"file": "bird3.mp3",
			"duration": 6.273991,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "birdcanyon",
			"keywords": "bird|afterring",
			"file": "birdcanyon.mp3",
			"duration": 16.018005,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "birdcry",
			"keywords": "bird|cry|afterring",
			"file": "birdcry.mp3",
			"duration": 12.151995,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "icebowedvibes1",
			"keywords": "z|bowedmetal|afterring|vibe",
			"file": "icebowedvibes1.mp3",
			"duration": 16.200998,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part001",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part001.mp3",
			"duration": 19.488,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part002",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part002.mp3",
			"duration": 11.616,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part003",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part003.mp3",
			"duration": 6.96,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part004",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part004.mp3",
			"duration": 22.776,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part005",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part005.mp3",
			"duration": 27.384,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part006",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part006.mp3",
			"duration": 27.12,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part007",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part007.mp3",
			"duration": 4.848,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part008",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part008.mp3",
			"duration": 29.568,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part009",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part009.mp3",
			"duration": 8.256,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part010",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part010.mp3",
			"duration": 18.816,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part011",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part011.mp3",
			"duration": 7.416,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part012",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part012.mp3",
			"duration": 11.184,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part013",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part013.mp3",
			"duration": 7.464,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part014",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part014.mp3",
			"duration": 8.976,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part015",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part015.mp3",
			"duration": 7.992,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part016",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part016.mp3",
			"duration": 7.704,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part017",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part017.mp3",
			"duration": 5.184,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part018",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part018.mp3",
			"duration": 7.56,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part019",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part019.mp3",
			"duration": 8.568,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part020",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part020.mp3",
			"duration": 11.448,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part021",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part021.mp3",
			"duration": 6.264,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part022",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part022.mp3",
			"duration": 34.872,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part023",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part023.mp3",
			"duration": 8.856,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part024",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part024.mp3",
			"duration": 7.992,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part025",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part025.mp3",
			"duration": 12.336,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part026",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part026.mp3",
			"duration": 6.96,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part027",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part027.mp3",
			"duration": 7.584,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "254349__cmorris035__vibraphone-bow-f-f_part028",
			"keywords": "vibe|bowedmetal|afterring|orchinstsample",
			"file": "254349__cmorris035__vibraphone-bow-f-f_part028.mp3",
			"duration": 7.056,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "373434__samulis__percussion-f2-gongscrape_mf",
			"keywords": "orchinstsample|gong|beat|percussion|afterring",
			"file": "373434__samulis__percussion-f2-gongscrape_mf.mp3",
			"duration": 3.551995,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "373499__samulis__percussion-g7-suscymb1-bow-4",
			"keywords": "orchinstsample|afterring|bowedmetal|cymbal",
			"file": "373499__samulis__percussion-g7-suscymb1-bow-4.mp3",
			"duration": 6.896009,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "373500__samulis__percussion-d3-suscymb1-cresc-long_v1",
			"keywords": "orchinstsample|afterring|bowedmetal|cymbal",
			"file": "373500__samulis__percussion-d3-suscymb1-cresc-long_v1.mp3",
			"duration": 12.878005,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		},
		{
			"id": "373511__samulis__percussion-b3-suscymb1-hitstick_f_rr1",
			"keywords": "orchinstsample|afterring|bowedmetal|cymbal",
			"file": "373511__samulis__percussion-b3-suscymb1-hitstick_f_rr1.mp3",
			"duration": 2.925011,
			"nchannels": 2,
			"rate": 44100,
			"type": "mp3",
			"bitrate": 16
		}
	],
	"score": [
		{
			"gain": 0.5,
			"padmin": 0,
			"padmax": 100,
			"delay": 0.2,
			"duration": 1,
			"nthreads": 4,
			"list": [
				[
					"longbell",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell11",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell13",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell2",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell6",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell9",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"374272__samulis__tubular-bells-e5-tb_hit_f5_v3_rr1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"374273__samulis__tubular-bells-c4-tb_hit_c4_v4_rr1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"375552__samulis__gong-gong_scrape_3",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				]
			]
		},
		{
			"gain": 0.5,
			"padmin": 0,
			"padmax": 100,
			"nthreads": 2,
			"list": [
				[
					"longbell",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell11",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell13",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell2",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell6",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell9",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"374272__samulis__tubular-bells-e5-tb_hit_f5_v3_rr1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"374273__samulis__tubular-bells-c4-tb_hit_c4_v4_rr1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"375552__samulis__gong-gong_scrape_3",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				]
			]
		},
		{
			"gain": 0.4,
			"padmin": 0,
			"padmax": 400,
			"delay": 0.3,
			"nthreads": 3,
			"list": [
				[
					"373178__samulis__f-horn-muted-sustain-g4-mohorn_mute_g3_v1_1",
					1,
					{
						"lowi": 0,
						"bassi": 0,
						"bassV": 0,
						"bassIV": 0,
						"I": 6,
						"II": 2,
						"majIII": 0,
						"miniii": 0,
						"IV": 2,
						"V": 3,
						"VI": 0,
						"majVII": 0,
						"minvii": 0,
						"VIII": 0,
						"lownoise": 0,
						"midnoise": 1,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"373243__samulis__f-horn-sustain-a3-mohorn_sus_a2_v1_1",
					1,
					{
						"lowi": 0,
						"bassi": 0,
						"bassV": 0,
						"bassIV": 0,
						"I": 6,
						"II": 2,
						"majIII": 0,
						"miniii": 0,
						"IV": 2,
						"V": 3,
						"VI": 0,
						"majVII": 0,
						"minvii": 0,
						"VIII": 0,
						"lownoise": 0,
						"midnoise": 1,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"373253__samulis__f-horn-sustain-a3-mohorn_sus_a2_v2_1",
					1,
					{
						"lowi": 0,
						"bassi": 0,
						"bassV": 0,
						"bassIV": 0,
						"I": 6,
						"II": 2,
						"majIII": 0,
						"miniii": 0,
						"IV": 2,
						"V": 3,
						"VI": 0,
						"majVII": 0,
						"minvii": 0,
						"VIII": 0,
						"lownoise": 0,
						"midnoise": 1,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				]
			]
		},
		{
			"gain": 0.2,
			"padmin": 0,
			"padmax": 400,
			"nthreads": 3,
			"list": [
				[
					"longbell",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell11",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell13",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell2",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell6",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell9",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bird0",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bird1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bird2",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bird3",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"birdcanyon",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"birdcry",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"icebowedvibes1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part001",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part002",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part003",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part004",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part005",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part006",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part007",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part008",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part009",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part010",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part011",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part012",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part013",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part014",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part015",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part016",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part017",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part018",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part019",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part020",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part021",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part022",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part023",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part024",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part025",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part026",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part027",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"254349__cmorris035__vibraphone-bow-f-f_part028",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"373434__samulis__percussion-f2-gongscrape_mf",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"373499__samulis__percussion-g7-suscymb1-bow-4",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"373500__samulis__percussion-d3-suscymb1-cresc-long_v1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"373511__samulis__percussion-b3-suscymb1-hitstick_f_rr1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"374272__samulis__tubular-bells-e5-tb_hit_f5_v3_rr1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"374273__samulis__tubular-bells-c4-tb_hit_c4_v4_rr1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				]
			]
		},
		{
			"gain": 0.4,
			"padmin": 0,
			"padmax": 100,
			"delay": 0,
			"duration": 0.8,
			"nthreads": 4,
			"list": [
				[
					"longbell",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell11",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell13",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell2",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell6",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"bell9",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"374272__samulis__tubular-bells-e5-tb_hit_f5_v3_rr1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"374273__samulis__tubular-bells-c4-tb_hit_c4_v4_rr1",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				],
				[
					"375552__samulis__gong-gong_scrape_3",
					1,
					{
						"lowi": 0,
						"bassi": 1,
						"bassV": 3,
						"bassIV": 3,
						"I": 6,
						"II": 0,
						"majIII": 0,
						"miniii": 6,
						"IV": 6,
						"V": 6,
						"VI": 0,
						"majVII": 0,
						"minvii": 4,
						"VIII": 2,
						"lownoise": 1,
						"midnoise": 3,
						"highnoise": 0,
						"noise": 0,
						"buzz": 0
					}
				]
			]
		}
	],
	"nx": 3,
	"ny": 3,
	"nz": 2,
	"xgrid": [
		0,
		0.5,
		1
	],
	"ygrid": [
		0,
		0.5,
		1
	],
	"pigments": {
		"red": "#8F0000",
		"yellow": "#ffcc00",
		"blue": "#006699",
		"bluegreen": "#006969",
		"black": "#000000",
		"warmblack": "#191918",
		"gray": "#484848",
		"lightgray": "#888888",
		"warmgray": "#4b4b44",
		"warmlightgray": "#656560",
		"white": "#ffffff",
		"warmwhite": "#fcfbe3",
		"warmlightwhite": "#fdfdf3",
		"warmlightwhiteveil": "rgba(253,253,243,0.8)",
		"richblack": "#010203",
		"richgray1": "#2a2a2b",
		"richgray2": "#4f4f50",
		"richgray3": "#777878",
		"richgray4": "#a2a3a3",
		"richgray5": "#d0d0d0",
		"richgray6": "#ffffff",
		"philippurple1": "#1A0D73",
		"philippurple2": "#59518C",
		"philippurple3": "#131159",
		"philipgreen1": "#3E5915",
		"philipgreen2": "#708C32"
	},
	"colors": [
		"#fdfdf3",
		"#191918"
	],
	"spicecolors": [
		"#fdfdf3",
		"#fdfdf3",
		"#191918",
		"#4b4b44",
		"#ffcc00"
	],
	"allcolors": [
		"#fdfdf3",
		"#fdfdf3",
		"#fdfdf3",
		"#fdfdf3",
		"#fdfdf3",
		"#fdfdf3",
		"#fdfdf3",
		"#fdfdf3",
		"#fdfdf3",
		"#fdfdf3",
		"#fdfdf3",
		"#fdfdf3",
		"#191918",
		"#191918",
		"#191918",
		"#191918",
		"#191918",
		"#191918",
		"#191918",
		"#191918",
		"#191918",
		"#484848",
		"#484848",
		"#8F0000",
		"#ffcc00",
		"#ffcc00"
	],
	"bookunits": "in",
	"bookwidth": 8,
	"bookheight": 8,
	"bookmargin": 1,
	"bookguttermargin": 1.2,
	"bleed": 0.125,
	"pixelsperunit": 72,
	"captionheight": 1,
	"cssstyles": "",
	"npoems": 80,
	"nstanzas": 3,
	"nlines": 4,
	"nchars": 48,
	"weights": [
		0,
		18,
		22,
		22,
		30,
		24,
		18,
		16,
		14,
		12,
		6,
		4,
		3,
		2,
		2,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1,
		1
	],
	"bookobj": {
		"title": "cyclone",
		"subtitle": "Sat Feb 17 2024",
		"description": "algorithmic sound & drawings",
		"rooturl": "https://cyclone.work",
		"authorurl": "https://mctavish.work/index.html",
		"author": "mctavish",
		"copyright": "Copyright ©2024 mctavish<br/>",
		"isbn": "ISBN: 00000<br/>",
		"publisher": ". . .",
		"sections": [],
		"poemids": [],
		"bookunits": "in",
		"bookwidth": 8,
		"bookheight": 8,
		"bookmargin": 1,
		"bookguttermargin": 1.2,
		"bleed": 0.125,
		"pixelsperunit": 72,
		"captionheight": 1,
		"cssstyles": ""
	},
	"filmobj": {
		"title": "cyclone",
		"subtitle": "Sat Feb 17 2024",
		"description": "algorithmic sound & drawings",
		"rooturl": "https://cyclone.work",
		"authorurl": "https://mctavish.work/index.html",
		"author": "mctavish",
		"copyright": "Copyright ©2024 mctavish<br/>",
		"isbn": "ISBN: 00000<br/>",
		"publisher": ". . .",
		"sections": [],
		"poemids": [],
		"bookmargin": 1,
		"bookguttermargin": 1.2,
		"bleed": 0.125,
		"bookunits": "in",
		"bookwidth": 8,
		"bookheight": 8,
		"pixelsperunit": 72,
		"captionheight": 1,
		"cssstyles": ""
	}
};
module.exports = input;